services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: commodity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/commodity-tracker/data
      - type: bind
        source: ./scripts/init.sql
        target: /docker-entrypoint-initdb.d/01-init.sql
      - type: bind
        source: ./scripts/bronze/ddl_bronze.sql
        target: /docker-entrypoint-initdb.d/02-ddl-bronze.sql

    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d commodity_db"]  
      interval: 10s
      timeout:  5s
      retries: 5    
  
  extractor:
    image: cpd-extractor #This image must be locally built in the specified name before execution. Use `Dockerfile_extractor` to compile the image
    depends_on: 
      - postgres
    volumes:
      - ./data:/commodity-tracker/data
      - ./scripts:/commodity-tracker/scripts
    networks:
      - etl-network

  loader:
    image: cpd-loader #This image must be locally built in the specified name before execution. Use `Dockerfile_loader` to compile the image

    depends_on: 
      postgres:
        condition: service_healthy
      extractor:
        condition: service_completed_successfully
    volumes:
      - ./data:/commodity-tracker/data
      - ./scripts:/commodity-tracker/scripts
    command: ["/commodity-tracker/data/landing_zone/",
              "myuser", #user name of the db 
              "secret", #password of the db
              "postgres", #db service name, ipaddress resolved by DNS
              "5432", #port where the db service is exposed
              "commodity_db", #database name
              "bronze", #schema name
              "bronze_prices", #table name
              "/commodity-tracker/data/archive/"] #address where to archive the processed files
    networks:
      - etl-network
  
  postgres-airflow-metadata:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: airflow_metadata
    ports:
      - "5433:5432"
    volumes:
      - pgdata-airflow:/var/lib/postgresql/data
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_user -d airflow_metadata"]  
      interval: 10s
      timeout:  5s
      retries: 5

  airflow-manager:
    image: airflow-with-docker:latest ##This image must be locally built in the specified name before execution. Use `Dockerfile_airflow` to compile the image
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg://airflow_user:secret@postgres-airflow-metadata:5432/airflow_metadata
      AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: False
      HOST_PWD: $PWD

      # Pass the mounted path as env var for Airflow tasks to use
      SHARED_DATA_PATH: /airflow-data
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts

      # Mount data volume - THIS MUST BE AN ABSOLUTE PATH ON YOUR HOST
      # Replace /absolute/path/to with the actual location of your docker-compose.yml parent directory
      # For example: /home/user/my-project:/airflow-data or /root/project:/airflow-data
      - /var/lib/docker/volumes/commodity-data/_data:/airflow-data
    ports:
      - "8080:8080"
    depends_on: 
      postgres-airflow-metadata:
        condition: service_healthy
    command: ["standalone"]  
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge

volumes:
  pgdata:
  pgdata-airflow:
  commodity-data:
